image: Visual Studio 2019 Preview
skip_tags: true
environment:
  matrix:
    - channel: nightly
      target: x86_64-pc-windows-msvc
    - channel: nightly
      target: i686-pc-windows-msvc
branches:
  only:
    - master
install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target% --profile minimal
  - cmd: set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
cache:
  - '%USERPROFILE%\.cargo'
build: false
test_script:
  # We run the suite once with all functionality enabled, and then once without
  # the default features to make sure `no_std` support has not been broken
  - cargo test --features="std" --target=%target%
  - cargo test --no-default-features --target=%target%
